name: petbacker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.14.0
  permission_handler: ^11.3.0
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  location: ^8.0.1
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0
  xml: ^6.6.1

dev_dependencies:
  bloc_lint: ^0.3.0
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true